# action.yml
name: "github-tag-action"
description: "git tag to repository if the version is not tagged."
author: "billgo <hi@billgo.me>"
inputs:
  version:
    description: 'Git Tag version'
    required: true
  github_token:
    description: 'use secrets.GITHUB_TOKEN'
    required: true
  git_commit_sha:
    description: 'Git commit SHA'
    required: false
  git_tag_prefix:
    description: "prefix for git tag. Example) 'v'"
    required: false
    default: ""
  github_repo:
    description: 'GitHub repository path. Example) azu/test'
    required: true
runs:
  using: 'node16'
  main: 'lib/index.js'
branding:
  icon: 'alert-octagon'
  color: 'blue'
